version: '3'

services:
  orderservice:
    container_name: orderservice
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - orderservice_db

  orderservice_db:
    image: mysql:8.0
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', "--init-connect='SET NAMES utf8mb4;'"]
    container_name: orderservice_db
    restart: always
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - ../../../var/orderservice/database:/var/lib/mysql
    ports:
      - "3306:3306"